feat(serieFilter): add filter for serie endpoint
WildCodeSchool/0523-RemFr-JavaAngular-P2-backend-myserieslib pull request #10
Opened 2023-07-06 15:20 UTC by LudivineSa

and category controller
Resolves #3

2023-07-06 15:22 UTC, SavageD2 approved these changes
Nous approuvons ce message

2023-07-06 15:23 UTC, Matthieu28 approved these changes

2023-07-06 15:40 UTC, bastienapp requested changes

2023-07-06 15:40 UTC, bastienapp commented on src/main/java/com/templateproject/api/controller/CategorieController.java
> +@RequestMapping("/categories")
Je crois que d'autres routes commencent par /api, voir si tu veux ajouter ça, ou si les autres enlèvent /api de leurs routes

2023-07-06 15:40 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Episode.java
> +    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
Je me demande s'il ne faut pas mettre cette annotation au niveau de la classe. À tester, peut-être que ça marche très bien comme ça !

2023-07-06 15:40 UTC, bastienapp commented on src/main/java/com/templateproject/api/service/SerieService.java
> +        if(title == null || title.equals("")){
Problème d'espacement, tu peux faire CTRL + MAJ + ALT + L pour corriger automatiquement tout le fichier

2023-07-07 12:22 UTC, SavageD2 approved these changes
Nous approuvons ce message

2023-07-07 12:24 UTC, bastienapp approved these changes
Changements validés

2023-07-07 12:38 UTC, merged